---
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  namespace: default
  name: nginx-service
  labels:
    kiali_wizard: traffic_shifting
  annotations: ~
spec:
  host: nginx-service.default.svc.cluster.local
  subsets:
    - name: vA
      labels:
        version: vA
      # Specific trafficPolicy - Enable if want this config for this specific subset
      # More options in: https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
    - name: vB
      labels:
        version: vB
      # Specific trafficPolicy - Enable if want this config for this specific subset
      # More options in: https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN

  # Global trafficPolicy - No config
  # trafficPolicy: ~

  # Global trafficPolicy - Enable if want this config for all subsets
  # More options in: https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB
  # trafficPolicy:
  #   loadBalancer:
  #     simple: ROUND_ROBIN

---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  namespace: default
  name: nginx-service
  labels:
    kiali_wizard: traffic_shifting
spec:
  http:
    - route:
        - destination:
            host: nginx-service.default.svc.cluster.local
            subset: vA
          weight: 75
        - destination:
            host: nginx-service.default.svc.cluster.local
            subset: vB
          weight: 25
  hosts:
    - nginx-service.default.svc.cluster.local
  gateways: ~
